### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by AbestSG** [HumanBrainED/NHP-BrainExtraction#2]
Dear Ting,

My name Si Gao. I am from University of Maryland, Baltimore.
I was trying to Custimize the model for my dataset, but I got ValueError from python.
![Screen Shot 2020-11-24 at 12 52 07 PM](https://user-images.githubusercontent.com/70385215/100132875-07ec7680-2e54-11eb-903a-6b145571981f.png)

I am new to BrainExtraction. May I ask how to correctly set up the arguments of trainSs_UNet.py? What's the difference between training images and validation images? What image files should I put in the following directories?

-trt1w /directory_of_the_training_images 
-trmsk /directory_of_the_training_image_masks
-vt1w /directory_of_the_validation_images 
-vmsk /directory_of_the_validation_image_masks

Thanks,
Si

**Comment by sandywang** [comment]
Hi,
Did you put NIfTI files (T1 images and the corresponding masks) in the folders? 
https://discuss.pytorch.org/t/num-samples-should-be-a-positive-integer-value-but-got-num-samples-0/56041/5
https://discuss.pytorch.org/t/valueerror-num-samples-should-be-a-positive-integer-value-but-got-num-samples-0/75639

These codes should automatically recognize all NIfTI files in the folders.

Best,
Xindi

**Comment by AbestSG** [comment]
Hi Xindi,

What's the difference between directory of training images and directory of training validation images?

Thanks,
Si

**Comment by AbestSG** [comment]
> Hi,
> Did you put NIfTI files (T1 images and the corresponding masks) in the folders?
> https://discuss.pytorch.org/t/num-samples-should-be-a-positive-integer-value-but-got-num-samples-0/56041/5
> https://discuss.pytorch.org/t/valueerror-num-samples-should-be-a-positive-integer-value-but-got-num-samples-0/75639
> 
> These codes should automatically recognize all NIfTI files in the folders.
> 
> Best,
> Xindi

Hi Xindi,

What's the difference between directory of training images and directory of training validation images?

Thanks,
Si

**Comment by AbestSG** [comment]
> Hi,
> Did you put NIfTI files (T1 images and the corresponding masks) in the folders?
> https://discuss.pytorch.org/t/num-samples-should-be-a-positive-integer-value-but-got-num-samples-0/56041/5
> https://discuss.pytorch.org/t/valueerror-num-samples-should-be-a-positive-integer-value-but-got-num-samples-0/75639
> 
> These codes should automatically recognize all NIfTI files in the folders.
> 
> Best,
> Xindi

Hi Xindi,

Yes, I did put NIFTI files in the directories, but what's the difference between directory of training images and directory of validation images?

Thanks,
Si

**Comment by sandywang** [comment]
The validation set is used to evaluate the performance of model during training, if you just want to update the model with a specified epoch you could ignore it. But the error you show should be induced by the wrong search of NIfTI files in the folders.

Best,
Xindi

**Comment by AbestSG** [comment]
Dear Xindi,

How many T1 images and the corresponding masks do I need to put in directory_of_the_training_images and directory_of_the_training_image_masks for updating a model. If I want to update a model for pig T1w images, which one could be the best initial model? Thanks for your help. 

Si

**Comment by AbestSG** [comment]
> The validation set is used to evaluate the performance of model during training, if you just want to update the model with a specified epoch you could ignore it. But the error you show should be induced by the wrong search of NIfTI files in the folders.
> 
> Best,
> Xindi

Dear Xindi,

How many T1 images and the corresponding masks do I need to put in directory_of_the_training_images and directory_of_the_training_image_masks for updating a model. If I want to update a model for pig T1w images, which one could be the best initial model? Thanks for your help.

Si

**Comment by TingsterX** [comment]
Hi Si,

In theory, the more the better. But we have human-to-macaque transfer-learning work decently with 2 only macaque data, and further updating with only 1 macaque. If you don't have many, then 1 or 2 as the training set without validation set is not bad to start. 

Regarding the mode, I would suggest using "Site-All-T-epoch_36_update_with_Site_6_plus_7-epoch_09.model" as the initial model b/c it was trained on heterogeneous macaque data across multiple sites.

Best,
Ting

**Comment by AbestSG** [comment]
After I ran the trainSs_UNet.py on my training_images, it generated 40 'model-xx-epoch' models. Which one could be the best model for brain mask prediction?

**Comment by AbestSG** [comment]
> Hi Si,
> 
> In theory, the more the better. But we have human-to-macaque transfer-learning work decently with 2 only macaque data, and further updating with only 1 macaque. If you don't have many, then 1 or 2 as the training set without validation set is not bad to start.
> 
> Regarding the mode, I would suggest using "Site-All-T-epoch_36_update_with_Site_6_plus_7-epoch_09.model" as the initial model b/c it was trained on heterogeneous macaque data across multiple sites.
> 
> Best,
> Ting

After I ran the trainSs_UNet.py on my training_images, it generated 40 'model-xx-epoch' models. Which one could be the best model for brain mask prediction?

**Comment by AbestSG** [comment]
> Hi Si,
> 
> In theory, the more the better. But we have human-to-macaque transfer-learning work decently with 2 only macaque data, and further updating with only 1 macaque. If you don't have many, then 1 or 2 as the training set without validation set is not bad to start.
> 
> Regarding the mode, I would suggest using "Site-All-T-epoch_36_update_with_Site_6_plus_7-epoch_09.model" as the initial model b/c it was trained on heterogeneous macaque data across multiple sites.
> 
> Best,
> Ting

Dear Ting,

May I ask how to highlight brain ROI after I obtain brain mask?
Like this
https://github.com/TingsterX/PRIME-DE/blob/master/BrainExtraction/release/1_train12.gif

Thanks,
Si

**Comment by TingsterX** [comment]
Re: After I ran the trainSs_UNet.py on my training_images, it generated 40 'model-xx-epoch' models. Which one could be the best model for brain mask prediction?

 If you have the validation dataset, the epoch that performs the best on the validation dataset would be selected. If no validation dataset, a few epochs (N>2 in our human to macaque model) are needed. Usually, the later epoch fits your training data better, but it could also overfit. Can try the 10th and 40th epoch. If the data is from the same scanner, it won't have a big difference.

Re: May I ask how to highlight brain ROI after I obtain brain mask?
try FSL command: overlay and slicer
